name: Fake Social Media Actions
on: [push, pull_request]
jobs:
  Example-Actions-Job:
    name: Exploring GitHub Actions
    runs-on: ubuntu-latest
    steps:
      # Display which event was triggered the workflow
      - run: echo "The job was triggered by a ${{ github.event_name }} event."

      # Display runner information
      - run: echo "Job now running on ${{ runner.os }} server hosted by GitHub"

      # Display information about the repository and branch
      - run: echo "Current branch and repository is named by ${{ github.ref }} and by ${{ github.repository }}by ${{ github.repository }}."

      # TODO: update to version 3
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: conditional step when event name is pull request
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "This is event is a Pull Request"

      - name: List files in the repo
        run: |
          pwd ${{ github.workspace }}

      - name: Setup Python
        uses: actions/setup-python@v3.1.4

      - name: Display dotnet version
        run: dotnet --version

      - name: List files in tool cache
        run: |
          ls ${{ runner.tool_cache }}

      - run: echo "This job's status is ${{ job.status }}."
